### ISSUE TITLE
userf-fiendly: rlang::parse_exprs(samples_to_keep_conditions) into AlpsNMR::filter

### ISSUE THREAD

**Issue by Francisco-madrid-gambin** [sipss/AlpsNMR#13]
To put the conditions_expr:

`samples_to_keep_conditions <- "Timepoint %in% c("preop", "3 months after surgery")"`
`conditions_expr <- rlang::parse_exprs(samples_to_keep_conditions)`
`nmr_dataset <- AlpsNMR::filter(nmr_dataset, !!!conditions_expr)`

within the AlpsNMR::filter function in a user-friendly manner

**Comment by zeehio** [comment]
I suggest to simplify the tutorial, we don't need the conditions to be in a string:

```
nmr_dataset <- filter(nmr_dataset,
                      Timepoint %in% c("preop", "3 months after surgery"))
```

What do you think?

**Comment by Francisco-madrid-gambin** [comment]
I think it is fine.
