### ISSUE TITLE
Provide the source code for the tutorial

### ISSUE THREAD

**Issue by zeehio** [sipss/AlpsNMR#17]
The tutorial should be a "prebuilt vignette with source code". The official documentation to do that is not very good, but I think I know how to do it.

@Francisco-madrid-gambin Did you make any change to the tutorial since the last time you emailed it to me? (If you did, can you send me the latest version please?)

**Comment by Francisco-madrid-gambin** [comment]
I am still modifying the tutorial and it should be the last thing to be generated to contain all the suggested changes. We need to include a more user-friendly script based on the other issues to get the final version of the tutorial and then, of course, will email you.

**Comment by Francisco-madrid-gambin** [comment]
We already have amended and solved this issue.
