### ISSUE TITLE
Review sample dataset

### ISSUE THREAD

**Issue by zeehio** [sipss/AlpsNMR#3]
The AlpsNMR package has 4 NMR spectra at `inst/dataset-demo`. These samples were provided by XXX in the MeOH_serum_extraction dataset and I do not have written permission to redistribute them.

- If they can be redistributed, update the `inst/dataset-demo/README.txt` with proper license information and fix the vignette https://github.com/zeehio/AlpsNMR/blob/dd098ed182245b6f423787732fba7b3872afc90c/vignettes/introduction-to-alpsnmr.Rmd#L60

- If the samples can't be redistributed, remove them and provide a replacement, or (less ideally) remove all the examples and tests that use them.

**Comment by Francisco-madrid-gambin** [comment]
Dataset has been reviewed and corresponds to quality control pooled plasma samples. We have Moco permission to include them in the package as long as we remove any relation.

**Comment by zeehio** [comment]
It's great the decision to keep the files has been taken.
Please don't forget to update [this file](https://github.com/sipss/AlpsNMR/blob/4a4a966dd023b395a14ef5d6e2e799219438d623/inst/dataset-demo/README.txt) :wink:

**Comment by Francisco-madrid-gambin** [comment]
Done. 
I do not detect any related keyword else but let's keep the issue open (?).

**Comment by zeehio** [comment]
Closes b475cf5a05fd0b392688040316f85131e019b47c

Hey Fran, if in the commit message you write "Closes #3" automatically the issue number 3 will be closed when you push it :wink:
