### ISSUE TITLE
R CMD check is failing on continuous integration

### ISSUE THREAD

**Issue by Francisco-madrid-gambin** [sipss/AlpsNMR#30]
After merging branch 'master', the package does not pass R-CMD-check

**Comment by zeehio** [comment]
The check runs on an OSX system, and apparently the speaq package has not yet been built on CRAN for R-4.0.0. Hopefully it will be rebuilt in the next few days, I have contacted the speaq maintainer and asked him if he could check what is going on.

If by next Thursday things don't change I will try to find time to make changes to the test environment.

AlpsNMR has a large number of transitive and intransitive dependencies (CRAN, BioConductor, github, gitlab). This makes AlpsNMR a fragile package, as it is more likely that one of those dependencies introduces a breaking change.

**Comment by zeehio** [comment]
The speaq package is now available for macOS. The checks should be passing now
