### ISSUE TITLE
to infer_dim_pulse_nuclei 

### ISSUE THREAD

**Issue by lazarosatiro** [sipss/AlpsNMR#38]
Why add one pulse sequence in this script?

Have these warnnings relatioonships with noesyp1d_split sequence.

Somebody can help me?

**Comment by Hgracia** [comment]
Hi @lazarosatiro, i don't know that script you mean

**Comment by lazarosatiro** [comment]
good afternoon and thanks for the reply, after finding your old one I tried to use your package to export some experimental data to the chemspec package. I use a pulse sequence that is not in the bruker library, when I use the "to_ chemospec" function, but it does not execute correctly indicating that I have to add this pulse sequence, but I don't know how to do this.

**Comment by zeehio** [comment]
It's a warning and in this case it's harmless. It won't appear in future versions (if @Hgracia agrees on my pull request)

Does the to_chemospec function work, regardless of this warning? If not, could you share a reproducible example?
