### ISSUE TITLE
Review DESCRIPTION

### ISSUE THREAD

**Issue by zeehio** [sipss/AlpsNMR#4]
Review the `DESCRIPTION` file, in particular de Authors. Read [this](http://r-pkgs.had.co.nz/description.html for further details.

You may want to add yourselves as authors, and also I should not be the maintainer (someone else should hold the `cre` role).

**Comment by Francisco-madrid-gambin** [comment]
Thank you for this. We added ourselves as authors. Luis is going to take the `cre` role.
