### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by breidan** [sipss/AlpsNMR#44]
Hi,
I want to use `AlpsNMR` to investigate a metabolomics study with several hundred measurements. Trying on a test set of just 10 measurements I run into memory problems very early on. 
Here is what I did:

```
Define the path to the dirs containing the data, here measurements of 10 honey samples:

>path<-"Data/Mahoney"
># the 1D data resides in the 10 subdirs
>datadirs<-paste0(list.dirs(path,recursive = FALSE),"/10")

Read in the NMR data:

>NMRdataset<-nmr_read_samples(datadirs)

>View(NMRdataset)

Get resolution and interpolate the data:

>nmr_ppm_resolution(NMRdataset)[[1]]

[1] 0.000156785

>NMRmatrix<-nmr_interpolate_1D(NMRdataset,axis=c(min=-5,max=10,by=nmr_ppm_resolution(NMRdataset)[[1]]))

Interpolating data_1r...


  |                                                                                      
  |                                                                                |   0%
  |                                                                                      
  |========                                                                        |  10%
  |                                                                                      
  |================                                                                |  20%
  |                                                                                      
  |========================                                                        |  30%
  |                                                                                      
  |================================                                                |  40%
  |                                                                                      
  |========================================                                        |  50%
  |                                                                                      
  |================================================                                |  60%
  |                                                                                      
  |========================================================                        |  70%
  |                                                                                      
  |================================================================                |  80%
  |                                                                                      
  |========================================================================        |  90%
  |                                                                                      
  |================================================================================| 100%

Look at the metadata:

>nmr_meta_get(NMRdataset)

Error: cannot allocate vector of size 76.3 Mb
```
At this point the 16 GB of the PC are used up. Any tips of what to do to process even more data?

Any help would be highly appreciated. Thanks

**Comment by Hgracia** [comment]
Hi @breidan,
it is extrange because 76 Mb is not so much.

Sometimes i had problems if the samples had duplicated names. Maybe you can rename your samples with just numbers to check if is related with this.

Tell me if it worked

**Comment by breidan** [comment]
@Hgracia,
76MB is a lot if the memory is already full. Could you be a bit more specific what you mean by duplicated sample names? I do not think there were duplicates. And how would that make the memory fill up?

**Comment by breidan** [comment]
@Hgracia ,
after your comment I dug a bit deeper and I think I know now what you meant. After reading in the data the `NMRdataset$metadata`  sublist all contain the element `NMRExperiments` which was set to"10" for all experiments. `dyplr::left_join` in `nmr_meta_get` then tried to create a data frame with 10^7 rows which caused the memory to fill up.

Since the directory structure seems to define the name of `NMRExperiment` and this directory structure is defined by the Bruker software it might be an idea to enable setting `NMRExperiment` during data reading through an argument.

**Comment by Hgracia** [comment]
Exactly, that's what I wanted to get to. Renaming the samples was just an idea to check if memory filling did not occur. I will see how to prevent this from happening again.

I hope that you can continue executing now
