### ISSUE TITLE
Error loading Bruker NMR data with `nmr_read_samples`

### ISSUE THREAD

**Issue by breidan** [sipss/AlpsNMR#45]
Hi, I am trying to load 200+ NMR measurements from a Bruker Ascend 400 using `nmr_read_samles`. Of all the samples it loads two ok and for the rest I get error messages like this:

> Error loading sample: C:\Users\Public\R\NMR\Data\HONEY_R\08312016\1110'FUN.VALUE' must be a vector

All those measurements were made with identical settings. For another batch of 300+ measurements with slightly different settings on the same instrument data import works flawlessly.

Any ideas why this happens and how to make it work?

Cheers
Andreas

**Comment by breidan** [comment]
Did some investigation myself. The difference between the two data which were loaded and the rest is that for the two the title file only contained a single character field while all the others contained two. I believe this is the offending code in `parse_title_file`:

> all_names <- vapply(lines_split, FUN = function(line) line[[1]], 
            FUN.VALUE = array)

FUN.VALUE must be character(1). Then it works.

**Comment by Hgracia** [comment]
Hi @breidan, sorry for the inconvinient that you had.

Thanks for share you issue, investigate on it and share the solution you found.
I will add it to the code so that it doesn't happen again

**Comment by Hgracia** [comment]
updated in version 3.1.4
