### ISSUE TITLE
Spectra import

### ISSUE THREAD

**Issue by RDAC93** [sipss/AlpsNMR#46]
Hi. My name is Ricardo and I work in the metabolomics field.
I'm used to perform metabolomics analysis using the AlpsNMR, but since the latest version I have been experience some problems in importing NMR  spectra . In this version, only half of my NMR spectra are imported where the other half are not.
It keeps giving me the same error: 

NMR <- nmr_read_samples_dir( "C:/Users/NMR 1/Desktop/LP_nmr/nmr/Spectra", format = "bruker", pulse_sequence = "CPMG", metadata_only = FALSE)

**'FUN.VALUE' must be a vector**

Warning messages:
1: In value[[3L]](cond) :
  Error loading sample: C:\Users\NMR 1\Desktop\LP_nmr\nmr\Spectra\LP_1026515_11

**Comment by zeehio** [comment]
Hi Ricardo, could you please provide a reproducible example? So it's easier for us to reproduce the issue you are seeing

**Comment by RDAC93** [comment]
Hi. Do you want me to send the data that I'm working with or just explain better what I'm doing ?

________________________________
De: Sergio Oller ***@***.***>
Enviado: 10 de junho de 2021 18:31
Para: sipss/AlpsNMR ***@***.***>
Cc: RDAC93 ***@***.***>; Author ***@***.***>
Assunto: Re: [sipss/AlpsNMR] Spectra import (#46)


Hi Ricardo, could you please provide a reproducible example? So it's easier for us to reproduce the issue you are seeing

**Comment by zeehio** [comment]
I would appreciate if you could provide a small self-contained example that triggers the error. If the problem appears when loading one sample please just provide just one. You probably don't need to send the whole dataset.

Besides it would be useful to have the output of `SessionInfo()` after running the example, so we know the versions of the packages you have installed.

**Comment by RDAC93** [comment]
Hi

I'm sending 2 NMR spectra to you and also a document that contains all the commands that I used to load the samples and the sessionInfo().

Best regards

Ricardo Conde

________________________________
De: Sergio Oller ***@***.***>
Enviado: 11 de junho de 2021 04:52
Para: sipss/AlpsNMR ***@***.***>
Cc: RDAC93 ***@***.***>; Author ***@***.***>
Assunto: Re: [sipss/AlpsNMR] Spectra import (#46)


I would appreciate if you could provide a small self-contained example that triggers the error. If the problem appears when loading one sample please just provide just one. You probably don't need to send the whole dataset.

Besides it would be useful to have the output of SessionInfo() after running the example, so we know the versions of the packages you have installed.

**Comment by Juniorrod2** [comment]
Hi. 
i'm also having the same problem with my NOESY spectrums. 
alos sending the console error and links for 2 of my spectra.

`'
> files <- fs::dir_ls("C:/Users/USUARIO/Desktop/esp")
> dataset <- nmr_read_samples(sample_names = files)

FUN.VALUE' must be a vector
'FUN.VALUE' must be a vector
Error in nmr_read_samples_bruker(sample_names = sample_names, metadata_only = metadata_only,  : 
  No samples loaded
In addition: Warning messages:
1: In value[[3L]](cond) :
  Error loading sample: C:\Users\USUARIO\Desktop\esp\20
2: In value[[3L]](cond) :
  Error loading sample: C:\Users\USUARIO\Desktop\esp\24
> `
download links for the spectra: 
https://www.dropbox.com/s/bxdxgtyqhx7xzxg/20.zip?dl=0
https://www.dropbox.com/s/492tqlco3tnuwsi/24.zip?dl=0

**Comment by RDAC93** [comment]
Hi

Can you tell me if you could fix the problem of the spectra importation to R ?

________________________________
De: Ricardo Conde ***@***.***>
Enviado: 11 de junho de 2021 11:17
Para: sipss/AlpsNMR ***@***.***>
Assunto: RE: [sipss/AlpsNMR] Spectra import (#46)

Hi

I'm sending 2 NMR spectra to you and also a document that contains all the commands that I used to load the samples and the sessionInfo().

Best regards

Ricardo Conde

________________________________
De: Sergio Oller ***@***.***>
Enviado: 11 de junho de 2021 04:52
Para: sipss/AlpsNMR ***@***.***>
Cc: RDAC93 ***@***.***>; Author ***@***.***>
Assunto: Re: [sipss/AlpsNMR] Spectra import (#46)


I would appreciate if you could provide a small self-contained example that triggers the error. If the problem appears when loading one sample please just provide just one. You probably don't need to send the whole dataset.

Besides it would be useful to have the output of SessionInfo() after running the example, so we know the versions of the packages you have installed.

**Comment by zeehio** [comment]
Hi, I was able to reproduce the error and fix it. 

While it is reviewed and merged into master (I guess it will be merged in a couple of days) you can find a working version of AlpsNMR at my branch in my fork. You can install it with:

```r
remotes::install_github("zeehio/AlpsNMR@f1130b0da603cd57ccb4cb301da05d9d242c8e3c")
```

That should work until the pull requests are merged. Once they are merged you can use:

```r
remotes::install_github("sipss/AlpsNMR")
```

And once it's released to Bioconductor you'll be able to install it as usual.

**Comment by RDAC93** [comment]
Thank you

________________________________
De: Sergio Oller ***@***.***>
Enviado: 15 de junho de 2021 15:40
Para: sipss/AlpsNMR ***@***.***>
Cc: RDAC93 ***@***.***>; Author ***@***.***>
Assunto: Re: [sipss/AlpsNMR] Spectra import (#46)


Hi, I was able to reproduce the error and fix it.

While it is reviewed and merged into master (I guess it will be merged in a couple of days) you can find a working version of AlpsNMR at my branch in my fork. You can install it with:

***@***.***")

That should work until the pull requests are merged. Once they are merged you can use:

remotes::install_github("sipss/AlpsNMR")

And once it's released to Bioconductor you'll be able to install it as usual.
