### ISSUE TITLE
function "to_ChemoSpec "

### ISSUE THREAD

**Issue by lazarosatiro** [sipss/AlpsNMR#49]
238 / 5000
Resultados de tradução
Guys, I need your help, I'm trying to use the to_ChemoSpec function, but after executing the function, the groups field doesn't pull loads the factors data.

What field do I have to modify for this data to be loaded? 
![Captura de tela 2021-07-30 151013](https://user-images.githubusercontent.com/56121189/127694583-27a5955b-cdbc-4a61-8e36-8ee16b0adacd.png)

**Comment by zeehio** [comment]
If I recall correctly, I wrote that function to have minimal compatibility with ChemoSpec, thinking that if I eventually needed more features from it I would improve it.

Its implementation is very simple as you can see at https://github.com/sipss/AlpsNMR/blob/8463cafaec5d4287dbd8e989fe62938776c9338e/R/utils.R#L208

I'm not that familiar with ChemoSpec. What does ChemoSpec expect to be in the `groups` attribute? If you help me understand what's needed I'll try to improve a bit the current implementation

**Comment by lazarosatiro** [comment]
@zeehio 


In ChemoSpec, there is an argument called "gr.crit" criteria for a group. A vector of strings that will be searched among the file/sample names to assign an individual spectrum to group membership.

This argument is filled by the attribute called "group" which is generated by the "to_ChemoSpec" function.

I imagine that to solve this problem, the function must read the "treatment" information available in the execel file, associating it with each of the experiments and after that fill the object "Spectra [[ 4 ]] ".

Thanks again for your attention and I apologize for the English.

**Comment by zeehio** [comment]
Hi @lazarosatiro,

Your English is good, don't worry. 👍 

Please check #50 where I implement a plausible solution. I included instructions for you to test that branch. If the branch has the functionality you need we will merge to make it available on the next release.

Thanks for reaching us
