### ISSUE TITLE
Describe why functions are prefixed with `nmr_` or `pipe_`

### ISSUE THREAD

**Issue by zeehio** [sipss/AlpsNMR#5]
https://github.com/sipss/AlpsNMR/blob/4a4a966dd023b395a14ef5d6e2e799219438d623/vignettes/introduction-to-alpsnmr.Rmd#L28-L31

To this paragraph one could add:

> The main reason why all exported functions have a prefix is to make it easy for the user to discover the functions from the package. By typing `nmr_` RStudio will return the list of exported functions. In the R terminal,  `nmr_`  followed by the tab key (⇥) twice will have the same effect. Other popular packages, follow similar approaches (e.g: `forcats`: `fct_*`, `stringr`: `str_*`).

**Comment by Francisco-madrid-gambin** [comment]
Thank you very much. 

This paragraph has been updated as proposed.
