### ISSUE TITLE
DESCRIPTION: Add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [sipss/AlpsNMR#64]
Hi, please consider adding fields URL and BugReports to your DESCRIPTION to make it easier to locate this repo from, say, https://www.bioconductor.org/packages/release/bioc/html/AlpsNMR.html.

**Comment by zeehio** [comment]
Done, sorry for not filling those. I hope it wasn't too much extra work. Thanks for reporting this as well!
